export const actionTypes = {
    GET_ALL_COINS:'GET_ALL_COINS',
    FILTER_BY_COIN_NAME:'FILTER_BY_COIN_NAME',
    FILTER_BY_COIN_PRICE:'FILTER_BY_COIN_PRICE',
    FILTER_BY_COIN_VOLUME:'FILTER_BY_COIN_VOLUME',
    FILTER_BY_PRICE_PERCENT_CHANGE:'FILTER_BY_PRICE_PERCENT_CHANGE'
}